---
title: "Exchange Rate Empirical Analysis"
output: html_document
date: "2023-05-24"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Empirical Analysis

```{r }
library(tidyverse)
library(readr)
library(readxl)
library(lubridate)
library(foreign)
epias_data_complete <- read_csv("epias_data_complete.csv")
```




## Now use the variables from Stata results and prepare the graphs.  

```{r}
##Create the graph using TVGC values
## Upload the overall data
library(readr)
tvgc_completed <- read_csv("tvgc_completed.csv") %>% 
  mutate(DATE = ymd(date))
```


```{r}
##Upload Critical Valueas
## Uplaod Values for Model 1
cv_model1 <- read_table("matrix_critical_values95_model1.csv")
names(cv_model1)[1] = "Variable"
names(cv_model1)[2] = "MaxWaldFWD"
names(cv_model1)[3] = "MaxWaldRO"
names(cv_model1)[4] = "MaxWaldREC"
model1_usd_fwd = cv_model1$MaxWaldFWD[1]
model1_grp_fwd = cv_model1$MaxWaldFWD[2]
model1_usd_ro = cv_model1$MaxWaldRO[1]
model1_grp_ro = cv_model1$MaxWaldRO[2]
model1_usd_rec = cv_model1$MaxWaldREC[1]
model1_grp_rec = cv_model1$MaxWaldREC[2]

## Upload the second model results
cv_model2 <- read_table("matrix_critical_values95_model2.csv")
names(cv_model2)[1] = "Variable"
names(cv_model2)[2] = "MaxWaldFWD"
names(cv_model2)[3] = "MaxWaldRO"
names(cv_model2)[4] = "MaxWaldREC"
model2_usd_fwd = cv_model2$MaxWaldFWD[1]
model2_grp_fwd = cv_model2$MaxWaldFWD[2]
model2_usd_ro = cv_model2$MaxWaldRO[1]
model2_grp_ro = cv_model2$MaxWaldRO[2]
model2_usd_rec = cv_model2$MaxWaldREC[1]
model2_grp_rec = cv_model2$MaxWaldREC[2]

cv_model3 <- read_table("matrix_critical_values95_model3.csv")
names(cv_model3)[1] = "Variable"
names(cv_model3)[2] = "MaxWaldFWD"
names(cv_model3)[3] = "MaxWaldRO"
names(cv_model3)[4] = "MaxWaldREC"
model3_usd_fwd = cv_model3$MaxWaldFWD[1]
model3_grp_fwd = cv_model3$MaxWaldFWD[2]
model3_usd_ro = cv_model3$MaxWaldRO[1]
model3_grp_ro = cv_model3$MaxWaldRO[2]
model3_usd_rec = cv_model3$MaxWaldREC[1]
model3_grp_rec = cv_model3$MaxWaldREC[2]
```

```{r}
##Upload Critical Valueas for 99th percentiles
## Uplaod Values for Model 1
cv_model199 <- read_table("matrix_critical_values99_model1.csv")
names(cv_model199)[1] = "Variable"
names(cv_model199)[2] = "MaxWaldFWD"
names(cv_model199)[3] = "MaxWaldRO"
names(cv_model199)[4] = "MaxWaldREC"
model1_usd_fwd99 = cv_model199$MaxWaldFWD[1]
model1_grp_fwd99 = cv_model199$MaxWaldFWD[2]
model1_usd_ro99 = cv_model199$MaxWaldRO[1]
model1_grp_ro99 = cv_model199$MaxWaldRO[2]
model1_usd_rec99 = cv_model199$MaxWaldREC[1]
model1_grp_rec99 = cv_model199$MaxWaldREC[2]

## Upload the second model results
cv_model299 <- read_table("matrix_critical_values99_model2.csv")
names(cv_model299)[1] = "Variable"
names(cv_model299)[2] = "MaxWaldFWD"
names(cv_model299)[3] = "MaxWaldRO"
names(cv_model299)[4] = "MaxWaldREC"
model2_usd_fwd99 = cv_model299$MaxWaldFWD[1]
model2_grp_fwd99 = cv_model299$MaxWaldFWD[2]
model2_usd_ro99 = cv_model299$MaxWaldRO[1]
model2_grp_ro99 = cv_model299$MaxWaldRO[2]
model2_usd_rec99 = cv_model299$MaxWaldREC[1]
model2_grp_rec99 = cv_model299$MaxWaldREC[2]

cv_model399 <- read_table("matrix_critical_values99_model3.csv")
names(cv_model399)[1] = "Variable"
names(cv_model399)[2] = "MaxWaldFWD"
names(cv_model399)[3] = "MaxWaldRO"
names(cv_model399)[4] = "MaxWaldREC"
model3_usd_fwd99 = cv_model399$MaxWaldFWD[1]
model3_grp_fwd99 = cv_model399$MaxWaldFWD[2]
model3_usd_ro99 = cv_model399$MaxWaldRO[1]
model3_grp_ro99 = cv_model399$MaxWaldRO[2]
model3_usd_rec99 = cv_model399$MaxWaldREC[1]
model3_grp_rec99 = cv_model399$MaxWaldREC[2]
```


```{r}
##Create the graph plot for comparing results
## Cretae the graph for Granger Causality from USD, GRF -> MCP
library(ggthemes)
library(ggplot2)
library(ggpubr)
alp = 0.2
alpcol = "blue"
alpsize = 0.75

mcp_graph_max = max(na.omit(tvgc_completed$M1_forward_mrusdtl))
mcp_fwd_usd <- tvgc_completed %>% 
  ggplot(aes(x = DATE, y = M1_forward_mrusdtl)) + 
  geom_line(colour = "red2", linewidth = 1) + theme_hc() + 
  xlab("Dates") + ylab("Test Statistic") + 
  labs(title = "EXC -> MCP ",
       subtitle = "(Forward Expanding)",
       caption = "(-) 95th; [..] 99th percentiles of Bootstrapped Test Statistics") +
  theme(axis.title.x = element_blank()) +
  geom_hline(yintercept = model1_usd_fwd, linetype = "dashed", color = "black", alpha = 0.9, linewidth = 1.25) + 
  geom_hline(yintercept = model1_usd_fwd99, linetype = "dotted", color = "black", alpha = 0.9, linewidth = 1.25) + 
  geom_vline(xintercept = as.Date("2019-07-26"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 19/75e dusuruldu
  geom_vline(xintercept = as.Date("2019-09-13"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 16.50e dusuruldu
  geom_vline(xintercept = as.Date("2019-10-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 14e dusuruldu
  geom_vline(xintercept = as.Date("2019-12-13"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 12e dusuruldu
  geom_vline(xintercept = as.Date("2020-01-17"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 11.25e dusuruldu
  geom_vline(xintercept = as.Date("2020-02-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 10.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-03-18"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 9.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-04-23"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 8.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-05-22"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 8.25e dusuruldu
  geom_vline(xintercept = as.Date("2020-09-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 10.25e cikti
  geom_vline(xintercept = as.Date("2020-11-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15e cikti
  geom_vline(xintercept = as.Date("2020-12-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 17e cikti
  geom_vline(xintercept = as.Date("2021-03-21"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 19e cikti
  geom_vline(xintercept = as.Date("2021-09-24"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 18 indi
  geom_vline(xintercept = as.Date("2021-10-22"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 16 indi
  geom_vline(xintercept = as.Date("2021-11-19"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15 indi
  geom_vline(xintercept = as.Date("2021-12-17"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15 indi
  geom_vline(xintercept = as.Date("2019-07-05"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Murat Cetinkaya gorevden alindi
  geom_vline(xintercept = as.Date("2020-11-06"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Murat UYSAL gorevden alindi
  geom_vline(xintercept = as.Date("2021-03-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Naci Agbal gorevden alindi 
  geom_vline(xintercept = as.Date("2021-10-14"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Iki abskan yrd gorevden alindi
  geom_vline(xintercept = as.Date("2020-11-09"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) +   ## Berat gorevden alindi
  geom_vline(xintercept = as.Date("2021-12-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## KKM baslangici
  annotate("rect", 
           xmin = as.Date("2019-07-05"),
           xmax = as.Date("2020-11-06"),
           ymin = 0, ymax = mcp_graph_max, fill = "#00CCFF", alpha = 0.2) +
  annotate("rect", 
           xmin = as.Date("2020-11-06"),
           xmax = as.Date("2021-03-20"),
           ymin = 0, ymax = mcp_graph_max, fill = "#FFCC33", alpha = 0.2) +
   annotate("rect", 
           xmin = as.Date("2021-03-20"),
           xmax = as.Date("2022-03-31"),
           ymin = 0, ymax = mcp_graph_max, fill = "#66CC00", alpha = 0.2)  
```

```{r}
##Create the graph plot for comparing results
## Cretae the graph for Granger Causality from USD -> MCP
library(ggthemes)
library(ggplot2)
library(ggpubr)
alp = 0.2
alpcol = "blue"
alpsize = 0.75

mcp_graph_max = max(na.omit(tvgc_completed$M1_rolling_mrusdtl))
mcp_ro_usd <- tvgc_completed %>%
  ggplot(aes(x = DATE, y = M1_rolling_mrusdtl )) + 
  geom_line(colour = "red2", linewidth = 1) + theme_hc() + 
  xlab("Dates") + ylab("Test Statistic") + 
  theme(axis.title.x = element_blank()) +
  geom_hline(yintercept = model1_usd_ro, linetype = "dashed", color = "black", alpha = 0.9, linewidth = 1.25) + 
  geom_hline(yintercept = model1_usd_ro99, linetype = "dotted", color = "black", alpha = 0.9, linewidth = 1.25) + 
 geom_vline(xintercept = as.Date("2019-07-26"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 19/75e dusuruldu
  geom_vline(xintercept = as.Date("2019-09-13"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 16.50e dusuruldu
  geom_vline(xintercept = as.Date("2019-10-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 14e dusuruldu
  geom_vline(xintercept = as.Date("2019-12-13"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 12e dusuruldu
  geom_vline(xintercept = as.Date("2020-01-17"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 11.25e dusuruldu
  geom_vline(xintercept = as.Date("2020-02-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 10.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-03-18"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 9.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-04-23"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 8.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-05-22"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 8.25e dusuruldu
  geom_vline(xintercept = as.Date("2020-09-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 10.25e cikti
  geom_vline(xintercept = as.Date("2020-11-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15e cikti
  geom_vline(xintercept = as.Date("2020-12-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 17e cikti
  geom_vline(xintercept = as.Date("2021-03-21"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 19e cikti
  geom_vline(xintercept = as.Date("2021-09-24"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 18 indi
  geom_vline(xintercept = as.Date("2021-10-22"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 16 indi
  geom_vline(xintercept = as.Date("2021-11-19"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15 indi
  geom_vline(xintercept = as.Date("2021-12-17"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15 indi
  geom_vline(xintercept = as.Date("2019-07-05"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Murat Cetinkaya gorevden alindi
  geom_vline(xintercept = as.Date("2020-11-06"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Murat UYSAL gorevden alindi
  geom_vline(xintercept = as.Date("2021-03-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Naci Agbal gorevden alindi 
  geom_vline(xintercept = as.Date("2021-10-14"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Iki abskan yrd gorevden alindi
  geom_vline(xintercept = as.Date("2020-11-09"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) +   ## Berat gorevden alindi
  geom_vline(xintercept = as.Date("2021-12-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## KKM baslangici
  annotate("rect", 
           xmin = as.Date("2019-07-05"),
           xmax = as.Date("2020-11-06"),
           ymin = 0, ymax = mcp_graph_max, fill = "#00CCFF", alpha = 0.2) +
  annotate("rect", 
           xmin = as.Date("2020-11-06"),
           xmax = as.Date("2021-03-20"),
           ymin = 0, ymax = mcp_graph_max, fill = "#FFCC33", alpha = 0.2) +
   annotate("rect", 
           xmin = as.Date("2021-03-20"),
           xmax = as.Date("2022-03-31"),
           ymin = 0, ymax = mcp_graph_max, fill = "#66CC00", alpha = 0.2)  +
    labs(title = "EXC -> MCP ",
       subtitle = "(Rolling Window)",
       caption = "(-) 95th; [..] 99th percentiles of Bootstrapped Test Statistics") 
```

```{r}
##Create the graph plot for comparing results
## Cretae the graph for Granger Causality from USD -> MCP Recursive
library(ggthemes)
library(ggplot2)
library(ggpubr)
alp = 0.2
alpcol = "blue"
alpsize = 0.75

mcp_graph_max = max(na.omit(tvgc_completed$M1_recursive_mrusdtl))
mcp_rec_usd <- tvgc_completed %>%
  ggplot(aes(x = DATE, y = M1_recursive_mrusdtl)) + 
  geom_line(colour = "red2", linewidth = 1) + theme_hc() + 
  xlab("Dates") + ylab("Test Statistic") + 
  theme(axis.title.x = element_blank()) +
  geom_hline(yintercept = model1_usd_rec, linetype = "dashed", color = "black", alpha = 0.9, linewidth = 1.25) + 
  geom_hline(yintercept = model1_usd_rec99, linetype = "dotted", color = "black", alpha = 0.9, linewidth = 1.25) + 
  geom_vline(xintercept = as.Date("2019-07-26"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 19/75e dusuruldu
  geom_vline(xintercept = as.Date("2019-09-13"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 16.50e dusuruldu
  geom_vline(xintercept = as.Date("2019-10-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 14e dusuruldu
  geom_vline(xintercept = as.Date("2019-12-13"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 12e dusuruldu
  geom_vline(xintercept = as.Date("2020-01-17"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 11.25e dusuruldu
  geom_vline(xintercept = as.Date("2020-02-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 10.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-03-18"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 9.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-04-23"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 8.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-05-22"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 8.25e dusuruldu
  geom_vline(xintercept = as.Date("2020-09-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 10.25e cikti
  geom_vline(xintercept = as.Date("2020-11-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15e cikti
  geom_vline(xintercept = as.Date("2020-12-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 17e cikti
  geom_vline(xintercept = as.Date("2021-03-21"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 19e cikti
  geom_vline(xintercept = as.Date("2021-09-24"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 18 indi
  geom_vline(xintercept = as.Date("2021-10-22"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 16 indi
  geom_vline(xintercept = as.Date("2021-11-19"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15 indi
  geom_vline(xintercept = as.Date("2021-12-17"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15 indi
  geom_vline(xintercept = as.Date("2019-07-05"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Murat Cetinkaya gorevden alindi
  geom_vline(xintercept = as.Date("2020-11-06"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Murat UYSAL gorevden alindi
  geom_vline(xintercept = as.Date("2021-03-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Naci Agbal gorevden alindi 
  geom_vline(xintercept = as.Date("2021-10-14"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Iki abskan yrd gorevden alindi
  geom_vline(xintercept = as.Date("2020-11-09"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) +   ## Berat gorevden alindi
  geom_vline(xintercept = as.Date("2021-12-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## KKM baslangici
  annotate("rect", 
           xmin = as.Date("2019-07-05"),
           xmax = as.Date("2020-11-06"),
           ymin = 0, ymax = mcp_graph_max, fill = "#00CCFF", alpha = 0.2) +
  annotate("rect", 
           xmin = as.Date("2020-11-06"),
           xmax = as.Date("2021-03-20"),
           ymin = 0, ymax = mcp_graph_max, fill = "#FFCC33", alpha = 0.2) +
   annotate("rect", 
           xmin = as.Date("2021-03-20"),
           xmax = as.Date("2022-03-31"),
           ymin = 0, ymax = mcp_graph_max, fill = "#66CC00", alpha = 0.2)  +
   labs(title = "EXC -> MCP ",
       subtitle = "(Recursive Evolving)",
       caption = "(-) 95th; [..] 99th percentiles of Bootstrapped Test Statistics")
```

```{r}
## Merge 3 Graphs
ggarrange(mcp_fwd_usd, mcp_ro_usd, mcp_rec_usd, ncol = 1, nrow =3) 
ggsave("mcp_usd_graph.png", width = 14, height = 20, units = "cm")
```

```{r}
## Now create the same for gas 
##Create the graph plot for comparing results
## Cretae the graph for Granger Causality from USD, GRP -> MCP
library(ggthemes)
library(ggplot2)
library(ggpubr)
alp = 0.2
alpcol = "blue"
alpsize = 0.75

mcp_graph_max = max(na.omit(tvgc_completed$M1_forward_mrgrftl))
mcp_fwd_grp <- tvgc_completed %>%
  ggplot(aes(x = DATE, y = M1_forward_mrgrftl)) + 
  geom_line(colour = "red2", linewidth = 1) + theme_hc() + 
  xlab("Dates") + ylab("Test Statistic") + 
  labs(title = "GRP -> MCP ",
       subtitle = "(Forward Expanding)",
       caption = "(-) 95th; [..] 99th percentiles of Bootstrapped Test Statistics") +
  theme(axis.title.x = element_blank()) +
  geom_hline(yintercept = model1_grp_fwd, linetype = "dashed", color = "black", 
             alpha = 0.9, linewidth = 1.25) + 
  geom_hline(yintercept = model1_grp_fwd99, linetype = "dotted", color = "black", 
             alpha = 0.9, linewidth = 1.25) + 
  geom_vline(xintercept = as.Date("2019-07-26"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 19/75e dusuruldu
  geom_vline(xintercept = as.Date("2019-09-13"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 16.50e dusuruldu
  geom_vline(xintercept = as.Date("2019-10-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 14e dusuruldu
  geom_vline(xintercept = as.Date("2019-12-13"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 12e dusuruldu
  geom_vline(xintercept = as.Date("2020-01-17"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 11.25e dusuruldu
  geom_vline(xintercept = as.Date("2020-02-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 10.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-03-18"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 9.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-04-23"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 8.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-05-22"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 8.25e dusuruldu
  geom_vline(xintercept = as.Date("2020-09-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 10.25e cikti
  geom_vline(xintercept = as.Date("2020-11-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15e cikti
  geom_vline(xintercept = as.Date("2020-12-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 17e cikti
  geom_vline(xintercept = as.Date("2021-03-21"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 19e cikti
  geom_vline(xintercept = as.Date("2021-09-24"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 18 indi
  geom_vline(xintercept = as.Date("2021-10-22"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 16 indi
  geom_vline(xintercept = as.Date("2021-11-19"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15 indi
  geom_vline(xintercept = as.Date("2021-12-17"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15 indi
  geom_vline(xintercept = as.Date("2019-07-05"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Murat Cetinkaya gorevden alindi
  geom_vline(xintercept = as.Date("2020-11-06"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Murat UYSAL gorevden alindi
  geom_vline(xintercept = as.Date("2021-03-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Naci Agbal gorevden alindi 
  geom_vline(xintercept = as.Date("2021-10-14"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Iki abskan yrd gorevden alindi
  geom_vline(xintercept = as.Date("2020-11-09"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) +   ## Berat gorevden alindi
  geom_vline(xintercept = as.Date("2021-12-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## KKM baslangici
  annotate("rect", 
           xmin = as.Date("2019-07-05"),
           xmax = as.Date("2020-11-06"),
           ymin = 0, ymax = mcp_graph_max, fill = "#00CCFF", alpha = 0.2) +
  annotate("rect", 
           xmin = as.Date("2020-11-06"),
           xmax = as.Date("2021-03-20"),
           ymin = 0, ymax = mcp_graph_max, fill = "#FFCC33", alpha = 0.2) +
   annotate("rect", 
           xmin = as.Date("2021-03-20"),
           xmax = as.Date("2022-03-31"),
           ymin = 0, ymax = mcp_graph_max, fill = "#66CC00", alpha = 0.2)  
```

```{r}
##Create the graph plot for comparing results
## Cretae the graph for Granger Causality from GRP -> MCP
library(ggthemes)
library(ggplot2)
library(ggpubr)
alp = 0.2
alpcol = "blue"
alpsize = 0.75

mcp_graph_max = max(na.omit(tvgc_completed$M1_rolling_mrgrftl))
mcp_ro_grp <- tvgc_completed %>%
  ggplot(aes(x = DATE, y = M1_rolling_mrgrftl)) + 
  geom_line(colour = "red2", linewidth = 1) + theme_hc() + 
  xlab("Dates") + ylab("Test Statistic") + 
  theme(axis.title.x = element_blank()) +
  geom_hline(yintercept = model1_grp_ro, linetype = "dashed", 
             color = "black", alpha = 0.9, linewidth = 1.25) + 
    geom_hline(yintercept = model1_grp_ro99, linetype = "dotted", 
             color = "black", alpha = 0.9, linewidth = 1.25) + 
  geom_vline(xintercept = as.Date("2019-07-26"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 19/75e dusuruldu
  geom_vline(xintercept = as.Date("2019-09-13"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 16.50e dusuruldu
  geom_vline(xintercept = as.Date("2019-10-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 14e dusuruldu
  geom_vline(xintercept = as.Date("2019-12-13"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 12e dusuruldu
  geom_vline(xintercept = as.Date("2020-01-17"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 11.25e dusuruldu
  geom_vline(xintercept = as.Date("2020-02-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 10.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-03-18"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 9.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-04-23"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 8.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-05-22"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 8.25e dusuruldu
  geom_vline(xintercept = as.Date("2020-09-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 10.25e cikti
  geom_vline(xintercept = as.Date("2020-11-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15e cikti
  geom_vline(xintercept = as.Date("2020-12-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 17e cikti
  geom_vline(xintercept = as.Date("2021-03-21"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 19e cikti
  geom_vline(xintercept = as.Date("2021-09-24"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 18 indi
  geom_vline(xintercept = as.Date("2021-10-22"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 16 indi
  geom_vline(xintercept = as.Date("2021-11-19"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15 indi
  geom_vline(xintercept = as.Date("2021-12-17"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15 indi
  geom_vline(xintercept = as.Date("2019-07-05"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Murat Cetinkaya gorevden alindi
  geom_vline(xintercept = as.Date("2020-11-06"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Murat UYSAL gorevden alindi
  geom_vline(xintercept = as.Date("2021-03-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Naci Agbal gorevden alindi 
  geom_vline(xintercept = as.Date("2021-10-14"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Iki abskan yrd gorevden alindi
  geom_vline(xintercept = as.Date("2020-11-09"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) +   ## Berat gorevden alindi
  geom_vline(xintercept = as.Date("2021-12-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## KKM baslangici
  annotate("rect", 
           xmin = as.Date("2019-07-05"),
           xmax = as.Date("2020-11-06"),
           ymin = 0, ymax = mcp_graph_max, fill = "#00CCFF", alpha = 0.2) +
  annotate("rect", 
           xmin = as.Date("2020-11-06"),
           xmax = as.Date("2021-03-20"),
           ymin = 0, ymax = mcp_graph_max, fill = "#FFCC33", alpha = 0.2) +
   annotate("rect", 
           xmin = as.Date("2021-03-20"),
           xmax = as.Date("2022-03-31"),
           ymin = 0, ymax = mcp_graph_max, fill = "#66CC00", alpha = 0.2)  +
    labs(title = "GRP -> MCP ",
       subtitle = "(Rolling Window)",
       caption = "(-) 95th; [..] 99th percentiles of Bootstrapped Test Statistics") 
```

```{r}
##Create the graph plot for comparing results
## Cretae the graph for Granger Causality from GRP -> MCP Recursive
library(ggthemes)
library(ggplot2)
library(ggpubr)
alp = 0.2
alpcol = "blue"
alpsize = 0.75

mcp_graph_max = max(na.omit(tvgc_completed$M1_recursive_mrgrftl))
mcp_rec_grp <- tvgc_completed %>% 
  ggplot(aes(x = DATE, y = M1_recursive_mrgrftl)) + 
  geom_line(colour = "red2", linewidth = 1) + theme_hc() + 
  xlab("Dates") + ylab("Test Statistic") + 
  theme(axis.title.x = element_blank()) +
  geom_hline(yintercept = model1_grp_rec, linetype = "dashed", color = "black", alpha = 0.9, linewidth = 1.25) + 
  geom_hline(yintercept = model1_grp_rec99, linetype = "dotted", color = "black", alpha = 0.9, linewidth = 1.25) + 
  geom_vline(xintercept = as.Date("2019-07-26"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 19/75e dusuruldu
  geom_vline(xintercept = as.Date("2019-09-13"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 16.50e dusuruldu
  geom_vline(xintercept = as.Date("2019-10-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 14e dusuruldu
  geom_vline(xintercept = as.Date("2019-12-13"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 12e dusuruldu
  geom_vline(xintercept = as.Date("2020-01-17"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 11.25e dusuruldu
  geom_vline(xintercept = as.Date("2020-02-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 10.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-03-18"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 9.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-04-23"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 8.75e dusuruldu
  geom_vline(xintercept = as.Date("2020-05-22"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 8.25e dusuruldu
  geom_vline(xintercept = as.Date("2020-09-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 10.25e cikti
  geom_vline(xintercept = as.Date("2020-11-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15e cikti
  geom_vline(xintercept = as.Date("2020-12-25"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 17e cikti
  geom_vline(xintercept = as.Date("2021-03-21"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 19e cikti
  geom_vline(xintercept = as.Date("2021-09-24"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 18 indi
  geom_vline(xintercept = as.Date("2021-10-22"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 16 indi
  geom_vline(xintercept = as.Date("2021-11-19"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15 indi
  geom_vline(xintercept = as.Date("2021-12-17"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## PAra politikasi faizi 15 indi
  geom_vline(xintercept = as.Date("2019-07-05"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Murat Cetinkaya gorevden alindi
  geom_vline(xintercept = as.Date("2020-11-06"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Murat UYSAL gorevden alindi
  geom_vline(xintercept = as.Date("2021-03-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Naci Agbal gorevden alindi 
  geom_vline(xintercept = as.Date("2021-10-14"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## Iki abskan yrd gorevden alindi
  geom_vline(xintercept = as.Date("2020-11-09"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) +   ## Berat gorevden alindi
  geom_vline(xintercept = as.Date("2021-12-20"), alpha = alp, col = alpcol,
             linetype = "dashed", linewidth = alpsize) + ## KKM baslangici
  annotate("rect", 
           xmin = as.Date("2019-07-05"),
           xmax = as.Date("2020-11-06"),
           ymin = 0, ymax = mcp_graph_max, fill = "#00CCFF", alpha = 0.2) +
  annotate("rect", 
           xmin = as.Date("2020-11-06"),
           xmax = as.Date("2021-03-20"),
           ymin = 0, ymax = mcp_graph_max, fill = "#FFCC33", alpha = 0.2) +
   annotate("rect", 
           xmin = as.Date("2021-03-20"),
           xmax = as.Date("2022-03-31"),
           ymin = 0, ymax = mcp_graph_max, fill = "#66CC00", alpha = 0.2)  +
   labs(title = "GRP -> MCP ",
       subtitle = "(Recursive Evolving)",
       caption = "(-) 95th; [..] 99th percentiles of Bootstrapped Test Statistics")
```



```{r}
## Merge 3 Graphs
ggarrange(mcp_fwd_grp, mcp_ro_grp, mcp_rec_grp, ncol = 1, nrow =3) 
ggsave("mcp_grp_graph.png", width = 14, height = 20, units = "cm")
```
